build:
  dependencies:
    override:
      - pip install -q flake8
      - pip install -q git+git://github.com/bartvm/pep257.git@numpy
  tests:
    override:
      - flake8 blocks bin tests examples
      - pep257 blocks bin tests examples --numpy --ignore=D100,D101,D102,D103
tools:
  external_code_coverage:
    runs: 4
    timeout: 3600
